variables:
- name: resourceGroupName
  value: la-bre-cicd
- name: logicAppName
  value: bre-logicappstd

stages:
- stage: Deploy_Infra
  jobs:
    - job: Bicep
      displayName: 'Deploy Infra'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Bicep Deployment'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'lab-bre-demo-rg-sc'
            subscriptionId: '$(subscriptionId)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: $(resourceGroupName)
            location: 'Australia East'
            templateLocation: 'Linked artifact'
            csmFile: './infra/bicep/deploy.bicep'
            # csmParametersFile: '$(Pipeline.Workspace)/infra/bicep/deploy.bicepparam'
            deploymentMode: 'Incremental'
            deploymentName: 'DeployPipelineTemplate'
- stage: Deploy_LogicApp
  jobs:
    - job: Deploy_Logic_App
      displayName: 'Deploy Logic App'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: CmdLine@2
          displayName: 'Build Logic App'
          inputs:
            script: |
              cd MyLogicAppRulesWorkspace\Function
              dotnet restore ./RulesFunction.csproj
              dotnet build ./RulesFunction.csproj
        - task: ArchiveFiles@2
          displayName: 'Create LogicApp zip package'
          inputs:
            rootFolderOrFile: 'MyLogicAppRulesWorkspace\LogicApp'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/logicapps.zip'
            replaceExistingArchive: true
        - task: CmdLine@2
          displayName: 'Deploy Logic App'
          inputs:
            script: |
              cd MyLogicAppRulesWorkspace\LogicApp
              az functionapp deploy --resource-group $(resourceGroupName) --name $(logicAppName) --src-path '$(Build.ArtifactStagingDirectory)/logicapps.zip' --type zip
