stages:
- stage: Deploy_Infra
  jobs:
    - job:
      displayName: 'Deploy Infra'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Bicep Deployment'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'lab-bre-demo-rg-sc'
            subscriptionId: '$(subscriptionId)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'la-bre-cicd'
            location: 'Australia East'
            templateLocation: 'Linked artifact'
            csmFile: './infra/bicep/deploy.bicep'
            # csmParametersFile: '$(Pipeline.Workspace)/infra/bicep/deploy.bicepparam'
            deploymentMode: 'Incremental'
            deploymentName: 'DeployPipelineTemplate'