stages:
- stage: Deploy_Infra
  jobs:
    - job: Bicep
      displayName: 'Deploy Infra'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Bicep Deployment'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'lab-bre-demo-rg-sc'
            subscriptionId: '$(subscriptionId)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'la-bre-cicd'
            location: 'Australia East'
            templateLocation: 'Linked artifact'
            csmFile: './infra/bicep/deploy.bicep'
            # csmParametersFile: '$(Pipeline.Workspace)/infra/bicep/deploy.bicepparam'
            deploymentMode: 'Incremental'
            deploymentName: 'DeployPipelineTemplate'
- stage: Deploy_LogicApp
  jobs:
    - job: Build_Logic_App
      displayName: 'Build Logic App'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: CmdLine@2
          displayName: 'Build Logic App'
          inputs:
            script: |
              cd MyLogicAppRulesWorkspace\Function
              dotnet restore ./RulesFunction.csproj
              dotnet build ./RulesFunction.csproj
