# Copy file `.env-template` to `.env` and update the values
# Set `MY_RULES_WORKFLOW_URL` to the URL of the locally running `MyRulesWorkflow` workflow via the "Overview" pane

###
# Test MyRulesWorkflow
@myRulesWorkflowUrl = {{ $dotenv MY_RULES_WORKFLOW_URL }}

POST {{ myRulesWorkflowUrl }}
Content-Type: application/json

{
    "inputXml": "<ns0:Root xmlns:ns0=\"http://BizTalk_Server_Project1.SchemaUser\"><UserDetails><Age>70</Age><Name>UserName</Name><zipCode>98053</zipCode></UserDetails><Status><Gold>false</Gold><Discount>0</Discount></Status></ns0:Root>",
    "purchaseAmount": 1100,
    "zipCode": "98052"
}

###
# Test PurchaseOrderWorkflow
@purchaseOrderWorkflowUrl = {{ $dotenv PURCHASE_ORDER_WORKFLOW_URL }}

POST {{ purchaseOrderWorkflowUrl }}
Content-Type: application/xml

<ns0:PurchaseOrder xmlns:ns0="http://EAISolution.PurchaseOrder">
    <Header>
        <ReqID>123456</ReqID>
        <Date>2024-12-20T05:47:00Z</Date>
    </Header>
    <Item>
        <Description>Ink cartridge refill</Description>
        <Quantity>400</Quantity>
        <UnitPrice>20</UnitPrice>
    </Item>
    <Status>New</Status>
</ns0:PurchaseOrder>
